### ISSUE TITLE
Cardinal components is in need of an update

### ISSUE THREAD

**Issue by Sunconure11** [CartoonishVillain/Eerie-Hauntings#2]
The latest build causes some crashes with other mods

**Comment by CartoonishVillain** [comment]
Thank you for letting me know! I'll update when I get off work!

**Comment by CartoonishVillain** [comment]
Fixed in EerieHauntings-FABRIC-1.0.2.1-1.18.1

**Comment by Sunconure11** [comment]
Probably want to update again, the cause of those crashes was with something one of the devs of CC was doing with experimental loom settings

**Comment by CartoonishVillain** [comment]
Ah darn. I'll update it when I'm off work again. Thank you for letting me know and for bearing with us here!
