### ISSUE TITLE
[Feature Request] No Effects While in Creative?

### ISSUE THREAD

**Issue by Darkosto** [CartoonishVillain/Eerie-Hauntings#3]
Hello! 

I've been enjoying the mod a ton but I was hoping you'd consider pausing the effects while the player is in Creative mode? As I'm working on configs or scripts, the haunting effects tend to get in the way. 

Thanks for your time!
Darkosto

**Comment by CartoonishVillain** [comment]
What version/mod loader are you running on? The effects should already be pausing in creative.

**Comment by CartoonishVillain** [comment]
This worked fine in the latest version for both platforms. I'm closing this ticket for now. I believe my mod may be being confused for another, or you may be using an outdated version. If neither is the case, feel free to correct me by updating this ticket with a version number and loader (forge/fabric)
